# Generated by Django 5.2.4 on 2025-10-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_is_paid_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
