# Generated by Django 5.2.4 on 2025-10-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_products_is_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
