# Generated by Django 5.2.4 on 2025-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_products_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
