# Generated by Django 5.2.6 on 2025-10-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_products_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
