# Generated by Django 5.2.4 on 2025-11-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='last_payout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
