# Generated by Django 5.2.4 on 2025-11-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_store_available_balance_store_last_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_paid_to_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
