# Generated by Django 5.2.4 on 2025-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, choices=[('Central', 'Central'), ('Copperbelt', 'Copperbelt'), ('Eastern', 'Eastern'), ('Luapula', 'Luapula'), ('Lusaka', 'Lusaka'), ('Muchinga', 'Muchinga'), ('Northern', 'Northern'), ('North-Western', 'North-Western'), ('Southern', 'Southern'), ('Western', 'Western')], max_length=50),
        ),
    ]
